	PROGRAM IMPRT
	REAL :: THJD, TINPH, T
	REAL, DIMENSION(1000) :: INPPH, CRVMDL, HJDS, GRBLS, SIGBLS, GRNUL, SIGNUL
	OPEN(3,FILE='./grunhut_bls.txt',STATUS='OLD')
	READ(3, *) NPH
	DO I=1, NPH
		READ(3, *) HJDS(I), INPPH(I), GRBLS(I), SIGBLS(I), GRNUL(I), SIGNUL(I)
		WRITE(6, *) HJDS(I), INPPH(I), GRBLS(I), SIGBLS(I), GRNUL(I), SIGNUL(I)
	ENDDO

	WRITE(6, *) HJDS(1)
	END PROGRAM